/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "load.h"


void
load_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  sum_1_arg;

	sum_1_arg.a = 2;
	sum_1_arg.b = 3;

#ifndef	DEBUG
	clnt = clnt_create (host, LOAD_PROG, LOAD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sum_1(&sum_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%d\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	load_prog_1 (host);
exit (0);
}
