/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "auth.h"

auth_output *
requestauth_1_svc(char **argp, struct svc_req *rqstp)
{
	static auth_output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

access_output *
requestaccess_1_svc(access_input *argp, struct svc_req *rqstp)
{
	static access_output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

status_code *
validateaction_1_svc(validate_input *argp, struct svc_req *rqstp)
{
	static status_code  result;

	/*
	 * insert server code here
	 */

	return &result;
}
