/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "auth.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

auth_output *
requestauth_1(char **argp, CLIENT *clnt)
{
	static auth_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REQUESTAUTH,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_auth_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

access_output *
requestaccess_1(access_input *argp, CLIENT *clnt)
{
	static access_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REQUESTACCESS,
		(xdrproc_t) xdr_access_input, (caddr_t) argp,
		(xdrproc_t) xdr_access_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

approve_output *
approvetoken_1(approve_input *argp, CLIENT *clnt)
{
	static approve_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, APPROVETOKEN,
		(xdrproc_t) xdr_approve_input, (caddr_t) argp,
		(xdrproc_t) xdr_approve_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

status_code *
validateaction_1(validate_input *argp, CLIENT *clnt)
{
	static status_code clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, VALIDATEACTION,
		(xdrproc_t) xdr_validate_input, (caddr_t) argp,
		(xdrproc_t) xdr_status_code, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
